timepath/config/routes.rb
Timepath::Application.routes.draw do
  get "home" =>'home#main'
  get "home/index"
  root "home#index"
  devise_for :users, :path => '', :path_names => { :sign_in => "login", :sign_out => "logout", :sign_up => "register"}

end

timepath/app/models/profile.rb
class Profile < ActiveRecord::Base
    include UUIDHelper
    has_one :user
end

timepath/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  include UUIDHelper
  before_create :create_profile
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  belongs_to :profile

  def create_profile 
    self.profile = Profile.new
  end
end

timepath/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

timepath/app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_filter :auth_user, :except => [:index]  
  def index
     redirect_to home_url if user_signed_in?
  end

  def main
  end

  def auth_user
    redirect_to home_url unless user_signed_in?
  end
end

timepath/app/controllers/profiles_controller.rb
class ProfilesController < Devise::RegistrationsController
    def create
        build_resource(sign_up_params)
        resource.profile = Profile.new
        logger.info("save")
        111
        if resource.save
          yield resource if block_given?
          if resource.active_for_authentication?
            set_flash_message :notice, :signed_up if is_flashing_format?
            sign_up(resource_name, resource)
            respond_with resource, :location => after_sign_up_path_for(resource)
          else
            set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_flashing_format?
            expire_data_after_sign_in!
            respond_with resource, :location => after_inactive_sign_up_path_for(resource)
          end
        else
          clean_up_passwords resource
          respond_with resource
        end
     end
end

timepath/app/helpers/application_helper.rb
module ApplicationHelper
end

timepath/app/helpers/home_helper.rb
module HomeHelper
    def resource_name
        :user
    end

      def resource
        @resource ||= User.new
      end

      def devise_mapping
        @devise_mapping ||= Devise.mappings[:user]
      end
end

timepath/app/views/home/index.html.erb
<div class='header'>
    <div class='header-content'>
        创建您的个人时间轴
    </div>
    
</div>
<div class='main'>
    <div class='blur-background-wrapper'>
    <div class='blur-background'>
      <div class='center-content'>
          <div class='board'>
              <!--register form-->

                <div class='register-board-shadow'>
                  <div class='register-board'>
                  <div class='register-board-form'>
                     <%= form_for(resource, :as => resource_name, :url => registration_path(resource_name)) do |f| %>
                    <%= devise_error_messages! %>
                    <div class='form-field'>
                      <div> <%= f.email_field :email, :autofocus => true, :placeholder=>"电子邮件" %></div>
                         <div id="mail-message" class='form-message'></div> 
                        <div><%= f.password_field :password, :placeholder=>"密码" %></div>
                          <div id="password-message" class='form-message'></div>
                        <div><%= f.password_field :password_confirmation, :placeholder=>"确认密码" %></div>
                          <div id="confirm-message" class='form-message'></div>
                        <div><%= f.submit "注册" %></div>
                   </div>
                    
                  <% end %>
                  </div>
                  </div>
              </div>
              <!--login form-->
              <div class='login-board-shadow'>
                  <div class='login-board'>
                    <div class='login-board-form'>
                       <%= form_for(resource, :as => resource_name, :url => session_path(resource_name)) do |f| %>
                        <div class='form-field'>
                            <div><%= f.email_field :email, :autofocus => true, :placeholder=>'电子邮件' %></div>
                            <div ><%= f.password_field :password, :placeholder=>'密码'%></div>
                            <% if devise_mapping.rememberable? -%>
                              <div class='checkbox-wrapper'><%= f.check_box :remember_me %> <%= f.label :记住登录状态  %></div>
                            <% end -%>

                            <div><%= f.submit "登录" %></div>
                        </div>

                      <% end %> 
                    </div>
                  </div>
              </div>
              <!--end form-->
          </div>


  
        <div class='login-button'>
            <div class='or'>或者</div>
            <button id='login-button'>登录</button>
        </div>
      </div>
 
        
    </div>
    </div>
</div>

<%= link_to "Sign out", destroy_user_session_path, :method => :delete %>

timepath/app/views/home/main.html.erb
<div class='container'>
    <div class='main-header'>
        <div class='main-header-left'></div>
        <div class='main-header-right'>
            <div id="signout-header">
                <%= link_to "注销", destroy_user_session_path, :method =>:delete %></div>
        </div>
    </div>
    <div class="main">
        <div class="timeline-container">
            <div id="timeline">
                <div id="time-spot">
                    <div class="cover-top"></div>
                    <div class="content">
                        <div class="content-container"></div>
                    </div>
                    <div class="cover-bottom"></div>
                </div>
                <div id="time-period">
                    <div class="content-background">
                        <div class="content-background-board"></div>
                        <div class="arrow-top"></div>
                        <div class="arrow-bottom"></div>
                        <div class="axis"></div>
                        <div class="shadow-seperator"></div>
                        <div class='drag-spec'></div>
                    </div>
                    <div class="time-content-container">
                        <div class="time-content">
                            <ul></ul>
                        </div>
                    </div>

                </div>
            </div>
        </div>

    </div>
    <div class='hover' init='false'>
        <div class='profile-container-board'>
            <div class='profile-board profile-panel'>
                <div class='profile-board-control'> <i class='glyphicons close'></i>
                </div>
                <h3>
                    完善个人信息
                    <a href="javascript:void()" id='ttyl'>稍后在说</a>
                </h3>
                <div class='form-field'>

                    <div>
                        <input placeholder='请问尊姓大名' autofocus='autofocus'/>
                    </div>
                    <div>
                        <div class='inline-div-group'>
                            <input class='inline-field' placeholder='年龄'/>
                            <input class='inline-field' placeholder='现居地' style='margin-left:19px'/>
                            <div>
                                <div>
                                    <textarea rows="6" cols="30" placeholder="来点个人介绍..." value=""></textarea>
                                </div>

                            </div>
                            <div>
                                <button class='profile-submit' id="profile-icon-button" onclick='showIconUploadBoard()'>上传头像</button>
                                <span style='margin:0 5px;'>或者</span>
                                <button class='profile-submit' id='profile-finish-button'>完成</button>
                            </div>
                        </div>

                    </div>

                </div>
            </div>

            <div class='icon-board profile-panel'>
                <div class='profile-board-control'> <i class='glyphicons close'></i>
                </div>
                <h3>
                    完善个人信息
                    <a class='fileupload'>
                        <span>点此上传</span>
                        <input type="file" class="upload" />
                    </a>
                </h3>
                <div class='form-field'>
                    <div class='inline-div-group'>
                         <div id='image-preview'></div>

                        <div>
                            <button class='profile-submit' id="profile-icon-button" onclick='showPreviousBoard()'>上一步</button>
                            <span style='margin:0 5px;'>或者</span>
                            <button class='profile-submit' id='profile-finish-button'>完成</button>
                        </div>                       
                    </div>

                </div>
            </div>
        </div>

    </div>
    <script type='text/javascript'>
    function showIconUploadBoard(){
        $(".profile-board").addClass("turnover")

    }

    function showPreviousBoard(){
        $(".profile-board").removeClass("turnover")
    }
</script>
    <%= javascript_include_tag "main", "data-turbolinks-track" =>
    true %>

timepath/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Timepath</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>